### ISSUE TITLE
working with r.js optimizer

### ISSUE THREAD

**Issue by houd1ni** [chadly/requirejs-web-workers#4]
Hi, I've tried the solution, but got worker file outside a build.

Also tried to add it explicitly by adding to `include` in config different ways, added and removed `define` wrapper from inside the worker. But it still loads async :/

Could you explain this behavior? Thanks in advance.

**Comment by houd1ni** [comment]
Is there some easy way, or I should write something using Blob as  "adapter" ?

**Comment by chadly** [comment]
This is [by design](https://github.com/chadly/requirejs-web-workers/blob/master/src/worker.js#L6). The [browser needs to load](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) the web worker script in a separate request.

**Comment by houd1ni** [comment]
Okay, just thought that maybe some workaround has been implemented (nonetheless saw the comment:). Thank you!
